In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [32]:
df = pd.read_csv('./datasets/Crucial_Elements.csv', index_col=0)
df = df.drop(df.index[0], axis=0)
df.tail()

,total_amount,trip_distance,fare_amount,tolls_amount,tip_amount,Brooklyn_PU,Manhattan_PU,Queens_PU,Staten_Island_PU,Bronx_DO,Brooklyn_DO,Manhattan_DO,Queens_DO,Staten_Island_DO,Mins_In_Ride
2020-06-30 19:00:00,15.954686,2.401137,9.870901,0.000000,1.833676,0.009099,0.976342,0.013649,0.0,0.011829,0.035487,0.915378,0.037307,0.0,9.337234
2020-06-30 20:00:00,15.718408,2.364177,9.769862,0.000000,1.701909,0.008299,0.957123,0.031812,0.0,0.015214,0.033195,0.900415,0.051176,0.0,9.098603
2020-06-30 21:00:00,14.993762,2.712161,10.621107,0.003571,1.616125,0.008929,0.939286,0.039286,0.0,0.044643,0.037500,0.871429,0.046429,0.0,9.762054
2020-06-30 22:00:00,15.704196,2.945819,11.237284,0.006034,1.635819,0.006466,0.922414,0.058190,0.0,0.040948,0.062500,0.825431,0.071121,0.0,10.113427
2020-06-30 23:00:00,16.295517,2.988082,11.428164,0.000000,1.597562,0.019178,0.893151,0.068493,0.0,0.038356,0.052055,0.797260,0.112329,0.0,9.967014

I created dummy variables in my data wrangling to help study what the data looks like and to check how they correlated to the target variable.

# Standardizing the magnitude

In [3]:
scalar = StandardScaler()
scaled_df = scalar.fit_transform(df)
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df.head()

,total_amount,trip_distance,fare_amount,tolls_amount,tip_amount,Brooklyn_PU,Manhattan_PU,Queens_PU,Staten_Island_PU,Bronx_DO,Brooklyn_DO,Manhattan_DO,Queens_DO,Staten_Island_DO,Mins_In_Ride
0,0.885796,-0.027912,0.437501,-0.214885,1.315357,0.374369,0.207345,-0.679667,-0.074548,-0.544620,0.333074,0.168653,-0.244830,-0.070958,1.689017
1,1.004708,0.127004,0.315116,-0.069906,1.267848,0.638116,-0.027822,-0.426011,-0.074548,-0.511267,0.784197,-0.155153,0.089778,-0.070958,0.989211
2,0.826532,0.251179,0.309303,-0.094525,1.025295,0.375325,0.077969,-0.338959,-0.074548,-0.455398,1.095317,-0.413523,0.378743,-0.070958,0.684245
3,0.771972,0.410612,0.394185,-0.043923,0.521331,0.417148,-0.028700,-0.051167,-0.074548,-0.453874,1.411391,-0.777335,0.987760,-0.070958,0.533587
4,0.750867,0.532663,0.394218,-0.100444,-0.281626,0.410655,-0.578600,1.409244,-0.074548,-0.440623,1.474249,-1.222272,2.057085,-0.070958,0.148210

In [18]:
len(df.columns)

15

In [35]:
scalar = StandardScaler()
indecies = df.index
X = df.drop('total_amount', axis=1)
y = df['total_amount']
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)
X_train.head()

# Join X_train and y_train into one dataframe
training_data = X_train.join(y_train)
# Same with the testing data
testing_data = X_test.join(y_test)

# Fit on the training data 
scalar.fit(training_data)

# Transform on the training and testing data
training_data = scalar.transform(training_data)
testing_data = scalar.transform(testing_data)

# Turning it back into a dataframe to be able to write it into a fiile
training_data = pd.DataFrame(training_data, columns=df.columns, index=indecies[:len(X_train)])
testing_data = pd.DataFrame(testing_data, columns=df.columns, index=indecies[len(X_train):])
testing_data.tail()

,total_amount,trip_distance,fare_amount,tolls_amount,tip_amount,Brooklyn_PU,Manhattan_PU,Queens_PU,Staten_Island_PU,Bronx_DO,Brooklyn_DO,Manhattan_DO,Queens_DO,Staten_Island_DO,Mins_In_Ride
2020-06-30 19:00:00,-0.235090,-0.131696,-0.234804,1.757663,-0.351197,0.591311,-0.630848,-0.071594,-0.720202,0.428733,0.257078,-0.397908,-0.069367,0.516952,0.532682
2020-06-30 20:00:00,-0.745289,-0.574427,-0.129806,0.502090,-0.321534,0.510580,-0.490913,-0.071594,-0.722540,-0.895218,0.959768,-0.840181,-0.069367,0.021763,-0.825966
2020-06-30 21:00:00,-0.595185,-0.635155,-0.037099,0.047802,-0.446498,0.436373,-0.161345,-0.071594,-0.555749,-0.587423,0.590648,-0.368588,-0.069367,-0.327877,-0.818028
2020-06-30 22:00:00,0.266817,0.037028,-0.271462,0.296296,-0.324876,0.135017,0.475288,-0.071594,-0.298095,0.746227,-0.559640,0.970866,-0.069367,-0.466077,0.513983
2020-06-30 23:00:00,0.572194,0.142182,-0.271462,-1.469716,-0.198958,0.515298,-0.614721,-0.071594,0.211361,-0.750208,0.341147,-0.310887,-0.069367,-0.925783,0.255008

In [36]:
training_data.to_csv('./datasets/Train_Data.csv')
testing_data.to_csv('./datasets/Test_Data.csv')